import sqlite3


class Database:
    @staticmethod
    def connect(name: str) -> sqlite3.Connection:
        """Returns a connection to a database.

        If the database does not exist it will create one before
        returning a connection.

        Args:
            name (str): name of the database.
        Returns:
            sqlite3.Connection: connection to database.
        """

        return sqlite3.connect(database=name)

    @staticmethod
    def execute(connection: sqlite3.Connection, query: str) -> bool:
        """Executes a query and returns whether it was successful.

        Args:
            connection (sqlite3.Connection): object connected to database.
            query (str): the query to execute.
        Returns:
            bool: True if query executed successfully otherwise False.
        """

        with connection:
            try:
                connection.cursor().execute(query)
                connection.commit()
                return True
            except sqlite3.Error as error:
                print(error)
                return False

    @staticmethod
    def create_table(connection: sqlite3.Connection, data: dict) -> bool:
        """Creates a table with the structure specified by the dict.

        The dict needs to have a particular structure for this to work:
        {
            "name": <table_name>,
            "columns": {
                "name": "<data_type> <constraints>"
                ...
            }
        }

        Args:
            connection (sqlite3.Connection): object connected to database.
            data (dict): table specifications.
        Returns:
            bool: True if operation was successful otherwise False.
        """
        columns = [f"{col_name} {col_type}" for col_name, col_type in data["columns"].items()]
        query = f"CREATE TABLE IF NOT EXISTS {data['name']} ({', '.join(columns)});"
        return Database.execute(connection, query)

    @staticmethod
    def insert_into_table(connection: sqlite3.Connection,
                          table: str, col: str, data: list) -> bool:
        """Inserts values into a specified table and column.

        Args:
            connection (sqlite3.Connection): object connected to database.
            table (str): name of table.
            col (str): name of column.
            data (list): list of values to be inserted.
        Returns:
            bool: True if all insertions were successful otherwise False.
        """

        query = f"INSERT INTO {table} ({col}) VALUES (?)"
        for value in data:
            try:
                connection.execute(query, (value,))
            except sqlite3.Error as error:
                print(error)
                return False
        return True

    from typing import Sequence

    @staticmethod
    def insert_into_table_multiple_cols(connection: sqlite3.Connection,
                                        table: str,
                                        columns: Sequence,
                                        data: Sequence) -> bool:
        """Inserts values into a specified table and column.

        Args:
            connection (sqlite3.Connection): object connected to database.
            table (str): name of table.
            col (str): name of column.
            data (list): list of values to be inserted.
        Returns:
            bool: True if all insertions were successful otherwise False.
        """

        # INSERT INTO table (col1, colN...) VALUES (value1, valueN...);

        query = f"INSERT INTO {table} ({tuple(columns)}) VALUES (?)"
        for value in data:
            try:
                connection.execute(query, (value,))
            except sqlite3.Error as error:
                print(error)
                return False
        return True

    @staticmethod
    def create_table_with_fk():
        """
        CREATE TABLE table_name (
          col_name data_type,
          col_pk   INT
          CONSTRAINT fk_pk FOREIGN KEY (col_pk)
          REFERENCES other_table(other_table_pk)
          ON DELETE SET NULL
          ON UPDATE CASCADE
        );
        """
        pass

    @staticmethod
    def alter_table_add_fk():
        """
        ALTER TABLE table_name
        ADD CONSTRAINT fk_id FOREIGN KEY (this_id)
        REFERENCES other_table(other_id)
        ON DELETE CASCADE;
        """
        pass

    @staticmethod
    def alter_table_drop_fk():
        """
        ALTER TABLE table_name
        DROP FOREIGN KEY fk_name;
        """
        pass

    @staticmethod
    def show_create_table_query():
        """
        SHOW CREATE TABLE table_name;
        """
        # This query will show the autogenerated CREATE TABLE query for your table,
        # and if you have an unnamed foreign key its name will be a part of this query.
        pass

    @staticmethod
    def select_from_table(connection: sqlite3.Connection, table: str, columns: list) -> list:
        """
        SELECT
          expr1 [AS alias1], ... exprN [AS aliasN]
        FROM
          table_name
        ;
        """

        pass

    @staticmethod
    def select_from_where_table(connection: sqlite3.Connection, table: str,
                                columns: list, filters: list) -> list:
        """
        SELECT
          expr1 [AS alias1], ... exprN [AS aliasN]
        FROM
          table_name
        WHERE
          logical_expression
        ;
        """

        pass

    @staticmethod
    def get_table_info(connection: sqlite3.Connection, table: str) -> bool:
        query = f"PRAGMA TABLE_INFO({table});"
        return Database.execute(connection, query)

    @staticmethod
    def insert_into_table_from(connection: sqlite3.Connection,
                               table_in: str, cols_in: list,
                               table_from: str, cols_from: list,
                               where: str = "") -> bool:
        """
        INSERT INTO table1 (column_1, column_2, ..., column_n)
        SELECT column_1, column_2, ..., column_n FROM table2
        WHERE condition;
        """
        pass
